### ISSUE TITLE
关于报错信息

### ISSUE THREAD

**Issue by jarryyen** [xtyuns/cloud189app-action#10]
作者你好,我已经按照您的部署教程使用aciton进行了部署.
我在我本地部署的错误结果如下:

[root cloud189app-action]# python3 action.py 
请输入账号: 189********
请输入登录密码: *********

189********:
    绑定设备ID不存在

**Comment by jarryyen** [comment]
并且 我已经关闭了天翼云盘的设备锁 的功能

**Comment by xtyuns** [comment]
可以将该账号的账号信息(用户名和密码)发送过来测试一下吗
邮箱: xtyuns@163.com

**Comment by jarryyen** [comment]
好的

**Comment by xtyuns** [comment]
那我暂时也无法定位你所述的问题, 而且你个人仓库中的 Actions 错误记录貌似是因为未正确配置运行参数所导致的

**Comment by jarryyen** [comment]
问题出现在登陆部分 , 稍后我打印一下啊

**Comment by jarryyen** [comment]
我发邮件给你吧

**Comment by xtyuns** [comment]
通过手动开启设备锁成功复现了该问题, 该问题的原因是所登录账号本身存在安全问题, 需要修改密码解除即可。
