### ISSUE TITLE
有时候会莫名其妙跑好几小时然后就达到免费上限了

### ISSUE THREAD

**Issue by SekiBetu** [xtyuns/cloud189app-action#18]
https://github.com/SekiBetu/cloud189app-action/actions/runs/1251545614

**Comment by xtyuns** [comment]
这种较小概率的事件无法确定其根本原因是 python 中的 http 请求出现了偶然的问题还是 Github Action 出现了偶然的问题，因此无法完全避免该问题。
但是可以通过 workflow 的设置增加单日内定时任务运行的次数来解决未签到的问题。
