### ISSUE TITLE
脚本运行说是说成功了但我还是能在云盘官网签到请大佬再复查下

### ISSUE THREAD

**Issue by dxzm2013gmailcom** [xtyuns/cloud189app-action#20]

**Comment by xtyuns** [comment]
1. 经过测试后, 脚本功能正常
2. 通过你的仓库运行日志可以看出来, 脚本运行过程中出现了异常, 请先排除异常原因
![Snipaste_2021-11-23_18-21-44](https://user-images.githubusercontent.com/41326335/143007612-aecb2e70-bed8-4a5c-812a-4ddfefc56e2f.png)

**Comment by dxzm2013gmailcom** [comment]
已经解决了谢谢
