### ISSUE TITLE
存储库闲置60天后自动禁用如何处理？

### ISSUE THREAD

**Issue by D33274D7C6** [xtyuns/cloud189app-action#28]
存储库闲置60天后自动禁用如何处理？
手动github邮件，说计划工作流在存储库闲置60天后自动禁用，今天一看，果然没了，需要重新更新username----password  xtyuns----123456，有办法全自动吗？

**Comment by xtyuns** [comment]
虽然我没有类似的需求，但是可能这个工具能够帮助你 [Keepalive Workflow](https://github.com/marketplace/actions/keepalive-workflow)

**Comment by D33274D7C6** [comment]
> 虽然我没有类似的需求，但是可能这个工具能够帮助你 [保持连接工作流](https://github.com/marketplace/actions/keepalive-workflow)

谢谢大佬，可惜我看不懂。我只能间隔50多天自动更新了。问题解决了，受限于我的问题无法使用罢了。
