### ISSUE TITLE
为什么actions任务显示This job was skipped

### ISSUE THREAD

**Issue by quanrenxiaohao** [xtyuns/cloud189app-action#29]
按照教程搞的，点star没有问题，但没办法每天自动了，点进去显示“This job was skipped”
![image](https://user-images.githubusercontent.com/100709930/198567660-78f01d1d-c02d-4bca-b9e6-6d5d249ac1d0.png)
![image](https://user-images.githubusercontent.com/100709930/198567705-0feb6c83-f5bf-4eb4-a66b-b699f10fb9cb.png)

**Comment by xtyuns** [comment]
尝试将该修改应用到你的代码库中: d4e0629de7fbcccd96a86fe723e01409820be176

**Comment by 610364023** [comment]
> 
修改代码后报错
![2022-11-02_14-01-39](https://user-images.githubusercontent.com/45279039/199410366-3b562011-2684-4d4e-9cdf-739b1324d8c1.jpg)

**Comment by xtyuns** [comment]
> > 
> 
> 修改代码后报错 ![2022-11-02_14-01-39](https://user-images.githubusercontent.com/45279039/199410366-3b562011-2684-4d4e-9cdf-739b1324d8c1.jpg)

按这个改动修改 b90a16553a5f6825a6aebb1845574ff84047318a
