### ISSUE TITLE
青龙面板 可以使用此脚本吗？

### ISSUE THREAD

**Issue by jk2008chd** [xtyuns/cloud189app-action#32]
作者大大可以出一个 个人家庭服务器青龙面板添加此脚本的教程吗？
另外使用GitHub后台运行脚本会不会 封号（天翼网盘账号）？
频繁登录 会不会有验证码（网盘登录），此脚本就会失效吧。

**Comment by xtyuns** [comment]
1. 请参考对应工具的使用文档
2. 理论来说不会，因为脚本每次执行都是以同一个设备信息来完成的
