### ISSUE TITLE
delete merge request

### ISSUE THREAD

**Issue by PraflyGod** [xtyuns/cloud189app-action#33]
请删除 这个无用的request
![image](https://user-images.githubusercontent.com/13954697/200733780-c056afda-8190-49f8-96ee-9703c61476de.png)

**Comment by xtyuns** [comment]
-> [参考文档](https://docs.github.com/cn/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-and-deleting-branches-within-your-repository#deleting-a-branch)
