### ISSUE TITLE
关于   “绑定设备ID不存在”

### ISSUE THREAD

**Issue by jarryyen** [xtyuns/cloud189app-action#9]
作者你好,我这里出现错误 “    绑定设备ID不存在 ”

请问是要获取自己的设备ID吗?

**Comment by xtyuns** [comment]
设备 ID 默认是根据账号信息生成的, 所以一般情况留空即可。

因为我没有在你的仓库中看到本项目的代码, 所以无法断定该错误的原因, 你能进一步提供详细的描述吗?
如: 错误的复现方法, 项目的运行配置信息等
